name = "pinochle-scorecard-api"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[durable_objects.bindings]]
name = "PINOCHLE_DURABLE_OBJECT"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]

[[ d1_databases ]]
binding = "DB"
database_name = "pinochle_durable_object_directory"
database_id = "6906ddda-deaf-472b-8cc7-9ef7b9aa6150"
