name = "pinochle-scorecard-api"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[durable_objects.bindings]]
name = "PINOCHLE_DURABLE_OBJECT"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]
